server:
  port: 8080
  context-path: /rent
  compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain
  session:
    timeout: 60

application:
  url: http://localhost
  session:
    redis:
      host: 62.80.167.165
      port: 6379
    cookie:
      name: UISESSION
      path: /

storage:
  host:
    scheme: http
    address: 62.80.167.165
    port: 8086
    context-path: /storage

search:
  host:
    address: search.dev.gup.ua
    port: 443
    scheme: https


uapay:
  int-service:
    host: 62.80.167.165
    port: 8282
    scheme: http
    base-path: /payment/api

mongo:
    db:
      uri: mongodb://gup:1qazxcft6@mongo-1.dev.gup.ua,mongo-2.dev.gup.ua,mongo-3.dev.gup.ua/heroku_lktlmxlq?replicaSet=GUP0
spring:
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true
  session:
    store-type: redis
  profiles:
    active: dev
  rabbitmq:
    host: 62.80.167.165
    port: 5672
    username: gup
    password: gup
    virtual-host: /gup-notify
  thymeleaf:
    cache: false
  output:
    ansi:
     enabled: always


security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: 7b5a38705d7b3562655925406a652e32
      clientSecret: 655f523128212d6e70634446224c2a48
      accessTokenUri: http://62.80.167.165:8081/oauth/api/oauth/token
      checkTokenUri: http://62.80.167.165:8081/oauth/api/oauth/check_token
      userAuthorizationUri: http://62.80.167.165:8081/oauth/api/oauth/authorize
    resource:
      userInfoUri: http://62.80.167.165:8081/oauth/api/users/principal
    sso: /api/user/login

#Mail Server Configuration for production
email:
  services:
    smtp:
      host: corp.gup.ua
      port: 25
      username: website@corp.gup.ua
      password: aJpDgDxPGX40Yf3H
      auth: true
      starttls:
        enable: true
